package me.hexillium.itemsets;

public enum ItemStat {
    Boots,
    ManaRegen,
    HealthRegen,
    Health,
    CriticalStrike,
    SpellDamage,
    Mana,
    Armor,
    SpellBlock,
    Damage,
    Lane,
    Jungle,
    LifeSteal,
    OnHit,
    AttackSpeed,
    Consumable,
    Active,
    Vision,
    Stealth,
    NonbootsMovement,
    Tenacity,
    SpellVamp,
    CooldownReduction,
    GoldPer,
    Aura,
    MagicPenetration,
    Slow,
    ArmorPenetration,
    Trinket,
    Bilgewater,
}
